In [1]:
import pandas as pd
import sqlite3

In [2]:
# 建立連線
con = sqlite3.connect('../data/test_db.sqlite')

In [3]:
# 把 311 資料寫進資料庫
requests = pd.read_csv('../data/311-service-requests.csv', dtype='unicode')
requests.to_sql('requests', con, if_exists='replace', index=False)

111069

In [4]:
pd.read_sql('SELECT * FROM requests LIMIT 5', con)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,26589651,10/31/2013 02:08:41 AM,NaN,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,11432,90-03 169 STREET,...,None,None,None,None,None,None,None,40.70827532593202,-73.79160395779721,"(40.70827532593202, -73.79160395779721)"
1,26593698,10/31/2013 02:01:04 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,11378,58 AVENUE,...,None,None,None,None,None,None,None,40.721040535628305,-73.90945306791765,"(40.721040535628305, -73.90945306791765)"
2,26594139,10/31/2013 02:00:24 AM,10/31/2013 02:40:32 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10032,4060 BROADWAY,...,None,None,None,None,None,None,None,40.84332975466513,-73.93914371913482,"(40.84332975466513, -73.93914371913482)"
3,26595721,10/31/2013 01:56:23 AM,10/31/2013 02:21:48 AM,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,10023,WEST 72 STREET,...,None,None,None,None,None,None,None,40.7780087446372,-73.98021349023975,"(40.7780087446372, -73.98021349023975)"
4,26590930,10/31/2013 01:53:44 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Vacant Lot,10027,WEST 124 STREET,...,None,None,None,None,None,None,None,40.80769092704951,-73.94738703491433,"(40.80769092704951, -73.94738703491433)"

In [5]:
pd.read_sql('SELECT "Complaint Type", "Borough" FROM requests WHERE "Borough" = \'BROOKLYN\' LIMIT 10', con)

             Complaint Type   Borough
0        Noise - Commercial  BROOKLYN
1  Noise - House of Worship  BROOKLYN
2                    Rodent  BROOKLYN
3           Illegal Parking  BROOKLYN
4    Street Light Condition  BROOKLYN
5  Noise - House of Worship  BROOKLYN
6        Noise - Commercial  BROOKLYN
7    Street Light Condition  BROOKLYN
8   Noise - Street/Sidewalk  BROOKLYN
9  Traffic Signal Condition  BROOKLYN

In [6]:
pd.read_sql('''
    SELECT "Borough", COUNT(*) as complaint_count 
    FROM requests 
    GROUP BY "Borough" 
    ORDER BY complaint_count DESC
''', con)

         Borough  complaint_count
0       BROOKLYN            32890
1      MANHATTAN            24288
2         QUEENS            22281
3          BRONX            19686
4    Unspecified             7107
5  STATEN ISLAND             4817